---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-omer-omer-io-v1-namespacelabel
  failurePolicy: Fail
  name: mnamespacelabel.kb.io
  rules:
  - apiGroups:
    - omer.omer.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespacelabels
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-omer-omer-io-v1-namespacelabel
  failurePolicy: Fail
  name: vnamespacelabel.kb.io
  rules:
  - apiGroups:
    - omer.omer.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespacelabels
  sideEffects: None
