# permissions for end users to edit namespacelabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: namespacelabel-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: projects
    app.kubernetes.io/part-of: projects
    app.kubernetes.io/managed-by: kustomize
  name: namespacelabel-editor-role
rules:
- apiGroups:
  - omer.omer.io
  resources:
  - namespacelabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - omer.omer.io
  resources:
  - namespacelabels/status
  verbs:
  - get
