apiVersion: omer.omer.io/v1
kind: NamespaceLabel
metadata:
    name: omer1
    namespace: omer
spec:
    labels:
        a: b
        kubernetes.io/metadata.name: sahar
        openshift.io: hara
        d: d